# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d2a89b3556748df1644505276c9da6a6"
application_url = "https://example.com"
embedded = true
name = "COD Order Watch"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quick-start-688d1411.myshopify.com"

[access_scopes]
scopes = "read_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"
